### ISSUE TITLE
No reply email voor de formulier (Araya Elektrotechiek)

### ISSUE THREAD

**Issue by zenitba** [zenitba/Herkansing-S4#5]
**To-Do**

- [x] Documentatie lezen
- [x] Youtube filmpjes kijken hoe je het connect met web3form
- [x] Toepassen in de code 
- [x] Custom no reply maken(optie)

**Bronnen**
>https://kit.svelte.dev/docs/form-actions
>https://expressjs.com/
>https://nodemailer.com/

**Comment by zenitba** [comment]
![Image](https://github.com/user-attachments/assets/bc943190-6361-4b55-affe-9089358c0716)

**Comment by zenitba** [comment]
[No reply code](https://github.com/zenitba/Meesterproef/commit/c8304b6e00a77519ca1df8fd1683d426a49b36ba)

Ik heb Nodemailer geinstalleerd, om automatisch een bevestigingsmail te sturen naar het e-mailadres van de gebruiker.
In deze e-mail laat ik de gebruiker weten dat hun bericht is ontvangen. Ik vertel ook dat de eigenaar met vaderschapsverlof is en zo snel mogelijk op hun bericht zal reageren.
